In [1]:
import numpy as np

The following matrix is the transition matrix of a random walk on a circle with N=4 points and transition probability p = 0.8

In [2]:
K = np.asarray([[0.2, 0.4, 0, 0.4], [0.4, 0.2, 0.4, 0], [0, 0.4, 0.2, 0.4], [0.4, 0, 0.4, 0.2]])
K

array([[ 0.2,  0.4,  0. ,  0.4],
       [ 0.4,  0.2,  0.4,  0. ],
       [ 0. ,  0.4,  0.2,  0.4],
       [ 0.4,  0. ,  0.4,  0.2]])

As a first approach to calculating the limit distribution, we take a high power of that matrix - the rows should then be close to the limit distribution. 

In [3]:
# 
# Be careful: K**20 would not be the right thing as this would take the power element-wise
# We could either use np.matmul in a loop or np.linalg.matrix_power
#
P = np.linalg.matrix_power(K,20)
P

array([[ 0.25000914,  0.24999086,  0.25000914,  0.24999086],
       [ 0.24999086,  0.25000914,  0.24999086,  0.25000914],
       [ 0.25000914,  0.24999086,  0.25000914,  0.24999086],
       [ 0.24999086,  0.25000914,  0.24999086,  0.25000914]])

No let us try to find the eigenvalues and eigenvectors of the transposed matrix (which, as K is symmetric, is in this case simply K itself).

In [4]:
w,v = np.linalg.eig(K)

According to the [scipy documentation](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.eig.html#numpy.linalg.eig), the first return value w is an array with the eigenvalues and the second value is an array such that column i is an eigenvector for the eigenvalue w[i]. So we expect that one of the entries in w is 1.0. We need to pick that column in v, and renormalize it so that the sum of its components is one.

In [5]:
w

array([-0.6,  1. ,  0.2,  0.2])

In [6]:
eigenvector = v[:,1] / np.sum(v[:,1])
eigenvector

array([ 0.25,  0.25,  0.25,  0.25])